import { Product, SchoolList } from './types';

export const CATEGORIES = [
  { id: 'todos', name: 'Todos' },
  { id: 'cuadernos', name: 'Cuadernos y Papelería' },
  { id: 'escritura', name: 'Escritura y Corrección' },
  { id: 'mochilas', name: 'Mochilas y Estuches' },
  { id: 'arte', name: 'Arte y Manualidades' },
  { id: 'tecnologia', name: 'Tecnología y Oficina' }
];

export const PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Cuaderno Cosido Línea Rayado Mascot RD',
    description: 'Cuaderno cosido de alta durabilidad con 100 hojas de papel de 60g. Portadas con variados diseños educativos, ideal para primaria y secundaria.',
    price: 125,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 142,
    stock: 500,
    brand: 'Mascot',
    tags: ['cuaderno', 'rayado', 'escolar', 'mascot'],
    isFeatured: true,
    storePrices: { sirena: 119, jumbo: 122, nacional: 129, plazalama: 125, bravo: 118, garrido: 109, ole: 115, carrefour: 130 }
  },
  {
    id: 'prod-02',
    name: 'Cuaderno de Caligrafía Mascot 60 Hojas',
    description: 'Cuaderno cosido especial con cuadrículas o guías de caligrafía vertical. Ayuda a los niños a mejorar y estructurar el tamaño de la letra.',
    price: 95,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 38,
    stock: 220,
    brand: 'Mascot',
    tags: ['caligrafia', 'escolar', 'cuaderno'],
    isFeatured: false,
    storePrices: { sirena: 92, jumbo: 89, nacional: 99, plazalama: 95, bravo: 90, garrido: 85, ole: 88, carrefour: 98 }
  },
  {
    id: 'prod-03',
    name: 'Caja de Lápices de Colores Prismacolor Junior x24',
    description: 'Colores surtidos intensos con mina cremosa y punta gruesa de 4mm. Perfectos para colorear, mezclar e ilustrar trabajos de arte escolar de alto impacto.',
    price: 495,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 165,
    stock: 120,
    brand: 'Prismacolor',
    tags: ['colores', 'colorear', 'arte', 'prismacolor', 'dibujo'],
    isFeatured: true,
    storePrices: { sirena: 480, jumbo: 475, nacional: 510, plazalama: 495, bravo: 465, garrido: 450, ole: 460, carrefour: 520 }
  },
  {
    id: 'prod-04',
    name: 'Mochila Escolar Porta-Laptop Ergonómica Oxford',
    description: 'Mochila escolar impermeable con soporte lumbar muscular acolchado, compartimento acolchado para laptop de hasta 15.6\', cierres de alta calidad y bolsillos laterales de malla.',
    price: 1850,
    category: 'mochilas',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 98,
    stock: 45,
    brand: 'Oxford Bags',
    tags: ['mochila', 'bolso', 'porta-laptop', 'Oxford'],
    isFeatured: true,
    storePrices: { sirena: 1795, jumbo: 1820, nacional: 1950, plazalama: 1850, bravo: 1780, garrido: 1690, ole: 1730, carrefour: 1990 }
  },
  {
    id: 'prod-05',
    name: 'Bolígrafos Bic Cristal Precision Azul (Caja de 10)',
    description: 'El clásico bolígrafo de bola con punta media de 1.0mm para trazos claros y constantes. Diseño hexagonal emblemático y cuerpo transparente.',
    price: 150,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 215,
    stock: 350,
    brand: 'Bic',
    tags: ['lapicero', 'boligrafo', 'bic', 'azul', 'oficina'],
    isFeatured: false,
    storePrices: { sirena: 145, jumbo: 140, nacional: 160, plazalama: 152, bravo: 138, garrido: 130, ole: 135, carrefour: 155 }
  },
  {
    id: 'prod-06',
    name: 'Estuche de Témperas Pelikan x12 Colores + Pincel',
    description: 'Témperas escolares solubles en agua de colores vibrantes y alta cobertura. No tóxicas y fáciles de lavar de la mayoría de telas escolares.',
    price: 320,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.4,
    reviewsCount: 52,
    stock: 80,
    brand: 'Pelikan',
    tags: ['pintura', 'tempera', 'pelikan', 'pincel', 'arte'],
    isFeatured: false,
    storePrices: { sirena: 299, jumbo: 315, nacional: 340, plazalama: 325, bravo: 295, garrido: 280, ole: 290, carrefour: 335 }
  },
  {
    id: 'prod-07',
    name: 'Resma de Papel Satinado Premium Letter / Carta 500H',
    description: 'Resma de papel de 20lb ideal para fotocopiadoras, impresoras láser e inyección de tinta. Blancura extrema de 96% para textos nítidos.',
    price: 295,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1603484477859-961a5e72d279?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 320,
    stock: 600,
    brand: 'Navigator',
    tags: ['resma', 'hojas', 'papel', 'carta', 'printing', 'oficina'],
    isFeatured: true,
    storePrices: { sirena: 285, jumbo: 290, nacional: 315, plazalama: 295, bravo: 280, garrido: 270, ole: 275, carrefour: 310 }
  },
  {
    id: 'prod-08',
    name: 'Calculadora Científica Casio fx-82MS 2nd Edition',
    description: 'Calculadora escolar científica estándar con pantalla de 2 líneas, 240 funciones integradas y tapa dura resistente a caídas accidentales.',
    price: 1150,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 184,
    stock: 75,
    brand: 'Casio',
    tags: ['calculadora', 'casio', 'cientifica', 'matematicas'],
    isFeatured: true,
    storePrices: { sirena: 1120, jumbo: 1095, nacional: 1190, plazalama: 1150, bravo: 1110, garrido: 1050, ole: 1080, carrefour: 1220 }
  },
  {
    id: 'prod-09',
    name: 'Lápiz Grafito Mongol #2 Premium (Caja de 12)',
    description: 'El lápiz amarillo colegial clásico con mina de grafito ultra lisa #2, suave borrador libre de látex que no mancha el papel al corregir.',
    price: 180,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 290,
    stock: 400,
    brand: 'PaperMate Mongol',
    tags: ['lapiz', 'mongol', 'grafito', 'escribir', 'borrador'],
    isFeatured: false,
    storePrices: { sirena: 175, jumbo: 170, nacional: 195, plazalama: 180, bravo: 165, garrido: 155, ole: 160, carrefour: 190 }
  },
  {
    id: 'prod-10',
    name: 'Juego de Geometría Escolar Maped 4 Piezas',
    description: 'Incluye regla de 30cm, escuadra de 45° de 21cm, cartabón de 60° de 21cm y transportador de 180°. Material plástico transparente de alta durabilidad.',
    price: 160,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 66,
    stock: 150,
    brand: 'Maped',
    tags: ['geometria', 'regla', 'escuadra', 'maped', 'matematicas'],
    isFeatured: false,
    storePrices: { sirena: 149, jumbo: 155, nacional: 170, plazalama: 165, bravo: 150, garrido: 140, ole: 145, carrefour: 172 }
  },
  {
    id: 'prod-11',
    name: 'Pegamento Escolar Líquido Elmers Blanco 4oz',
    description: 'Pegamento de secado rápido, transparente e hiper-fácil de lavar. Ideal para pegar papel, cartón de maquetas, madera escolar y manualidades escolares.',
    price: 110,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 88,
    stock: 190,
    brand: "Elmer's",
    tags: ['pegamento', 'silicon', 'elmers', 'manualidad', 'arte'],
    isFeatured: false,
    storePrices: { sirena: 99, jumbo: 105, nacional: 115, plazalama: 110, bravo: 102, garrido: 95, ole: 98, carrefour: 114 }
  },
  {
    id: 'prod-12',
    name: 'Corrector en Cinta Liquid Paper Dryline Pro',
    description: 'Cinta correctora seca de aplicación rápida que permite escribir de inmediato sobre ella. Ancho de cinta de 5mm, de diseño ergonómico muy cómodo.',
    price: 145,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 74,
    stock: 140,
    brand: 'Liquid Paper',
    tags: ['corrector', 'cinta', 'liquid', 'oficina', 'escolar'],
    isFeatured: false,
    storePrices: { sirena: 139, jumbo: 135, nacional: 150, plazalama: 145, bravo: 132, garrido: 125, ole: 129, carrefour: 152 }
  },
  {
    id: 'prod-13',
    name: 'Bloque de Plastilina Faber-Castell 10 Colores',
    description: 'Plastilina de base de cera que no se seca jamás. Textura suave ideal para moldear figuras anatómicas, geográficas o proyectos de preescolar.',
    price: 210,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1560421683-6856ea585c78?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 45,
    stock: 95,
    brand: 'Faber-Castell',
    tags: ['plastilina', 'manualidades', 'faber-castell', 'color', 'modelar'],
    isFeatured: false,
    storePrices: { sirena: 195, jumbo: 205, nacional: 220, plazalama: 215, bravo: 198, garrido: 185, ole: 190, carrefour: 222 }
  },
  {
    id: 'prod-14',
    name: 'Tijera Escolar Punta Roma Maped Koopy 5"',
    description: 'Tijera ergonómica asistida por resorte para niños que se inician en el recorte manual. Puntas completamente redondeadas de seguridad certificada.',
    price: 90,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1503428526543-45d268143786?q=80&w=600&auto=format&fit=crop',
    rating: 4.4,
    reviewsCount: 51,
    stock: 110,
    brand: 'Maped',
    tags: ['tijera', 'cortar', 'seguridad', 'maped'],
    isFeatured: false,
    storePrices: { sirena: 85, jumbo: 89, nacional: 95, plazalama: 92, bravo: 84, garrido: 78, ole: 80, carrefour: 94 }
  },
  {
    id: 'prod-15',
    name: 'Marcador Resaltador Faber-Castell Pastel (Set de 4)',
    description: 'Marcador resaltador con punta biselada fina de 3 trazos diferentes. Tintas atenuadas tipo color pastel elegantes para apuntes estéticos.',
    price: 250,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 118,
    stock: 195,
    brand: 'Faber-Castell',
    tags: ['resaltador', 'pastel', 'destacador', 'faber-castell', 'apuntes'],
    isFeatured: true,
    storePrices: { sirena: 235, jumbo: 240, nacional: 265, plazalama: 250, bravo: 230, garrido: 215, ole: 225, carrefour: 260 }
  },
  {
    id: 'prod-16',
    name: 'Sacapuntas Metálico Maped con Depósito',
    description: 'Sacapuntas de metal duradero de doble entrada con depósito recolector de virutas de plástico irrompible.',
    price: 85,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1141?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 42,
    stock: 310,
    brand: 'Maped',
    tags: ['sacapuntas', 'afilador', 'lapiz', 'deposito'],
    isFeatured: false,
    storePrices: { sirena: 79, jumbo: 82, nacional: 89, plazalama: 85, bravo: 78, garrido: 70, ole: 75, carrefour: 90 }
  },
  {
    id: 'prod-17',
    name: 'Borradores de Goma Faber-Castell (Caja de 2)',
    description: 'Borrador suave libre de PVC de altísima calidad para lápices de grafito. No mancha el papel escolar ni deja rastro.',
    price: 70,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1588611843236-407421ac1929?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 104,
    stock: 450,
    brand: 'Faber-Castell',
    tags: ['borrador', 'goma', 'limpiar', 'faber-castell'],
    isFeatured: false,
    storePrices: { sirena: 65, jumbo: 62, nacional: 74, plazalama: 70, bravo: 60, garrido: 55, ole: 58, carrefour: 72 }
  },
  {
    id: 'prod-18',
    name: 'Cartuchera Escolar de Doble Cierre Oxford',
    description: 'Cartuchera de tela premium de alta resistencia, con doble cremallera y espacio suficiente para más de 40 lápices, reglas y accesorios escolares.',
    price: 350,
    category: 'mochilas',
    image: 'https://images.unsplash.com/photo-1569003339405-ea396a5a8a90?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 61,
    stock: 125,
    brand: 'Oxford Bags',
    tags: ['cartuchera', 'estuche', 'lapices', 'oxford'],
    isFeatured: true,
    storePrices: { sirena: 335, jumbo: 340, nacional: 375, plazalama: 350, bravo: 325, garrido: 295, ole: 310, carrefour: 365 }
  },
  {
    id: 'prod-19',
    name: 'Papel Contact Transparente Forra-Libros (2 metros)',
    description: 'Papel adhesivo transparente de alta densidad para forrar y proteger de raspaduras accidentales los libros y cuadernos escolares.',
    price: 195,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1603484477859-961a5e72d279?q=80&w=600&auto=format&fit=crop',
    rating: 4.4,
    reviewsCount: 89,
    stock: 200,
    brand: 'Kores',
    tags: ['papel', 'contact', 'libros', 'forrar', 'protector'],
    isFeatured: false,
    storePrices: { sirena: 185, jumbo: 189, nacional: 210, plazalama: 195, bravo: 180, garrido: 165, ole: 175, carrefour: 205 }
  },
  {
    id: 'prod-20',
    name: 'Carpeta Escolar de Tres Aros 1.5" Wilson Jones',
    description: 'Carpeta de hojas intercambiables con lomo reforzado de 1.5 pulgadas y herrajes metálicos de alta calidad para organización escolar.',
    price: 240,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 57,
    stock: 180,
    brand: 'Wilson Jones',
    tags: ['carpeta', 'tres aros', 'argollas', 'Wilson Jones'],
    isFeatured: false,
    storePrices: { sirena: 225, jumbo: 230, nacional: 255, plazalama: 240, bravo: 220, garrido: 200, ole: 210, carrefour: 250 }
  },
  {
    id: 'prod-21',
    name: 'Cuaderno de Cuadros Mascot 100 Hojas (Matemáticas)',
    description: 'Cuaderno cosido con cuadrículas de 5mm ideal para matemáticas, física o geometría. Hojas de 60g de alta resistencia que evitan la filtración de tinta.',
    price: 135,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1531346878377-a5ec20888e23?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 88,
    stock: 350,
    brand: 'Mascot',
    tags: ['cuadros', 'cuaderno', 'matematicas', 'mascot'],
    isFeatured: false,
    storePrices: { sirena: 129, jumbo: 132, nacional: 139, plazalama: 135, bravo: 128, garrido: 120, ole: 122, carrefour: 140 }
  },
  {
    id: 'prod-22',
    name: 'Block de Dibujo de Cartulinas Súper Saro x20',
    description: 'Block escolar con 20 cartulinas de colores surtidos de alta densidad (120g). Perfecto para recortes, maquetas y trabajos creativos de manualidades artísticas.',
    price: 190,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 42,
    stock: 155,
    brand: 'Saro',
    tags: ['cartulina', 'block', 'dibujo', 'colores', 'manualidades'],
    isFeatured: false,
    storePrices: { sirena: 180, jumbo: 185, nacional: 205, plazalama: 190, bravo: 178, garrido: 165, ole: 170, carrefour: 210 }
  },
  {
    id: 'prod-23',
    name: 'Creyones de Cera Crayola de 24 Colores No Tóxicos',
    description: 'Crayones clásicos con excelente cobertura de color y alta resistencia a quebraduras. No tóxicos y seguros para el uso infantil en preescolar y primaria.',
    price: 215,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 194,
    stock: 240,
    brand: 'Crayola',
    tags: ['crayones', 'cuerda', 'crayola', 'colores', 'preescolar'],
    isFeatured: true,
    storePrices: { sirena: 205, jumbo: 198, nacional: 228, plazalama: 215, bravo: 210, garrido: 189, ole: 195, carrefour: 230 }
  },
  {
    id: 'prod-24',
    name: 'Marcadores Lavables Crayola Colores Clásicos x10',
    description: 'Marcadores con punta cónica ultra duradera que permite trazos gruesos o delgados. Tinta de base de agua 100% lavable de la piel de tus hijos.',
    price: 295,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 110,
    stock: 140,
    brand: 'Crayola',
    tags: ['marcadores', 'plumones', 'crayola', 'lavables', 'colores'],
    isFeatured: false,
    storePrices: { sirena: 285, jumbo: 280, nacional: 310, plazalama: 295, bravo: 290, garrido: 260, ole: 270, carrefour: 320 }
  },
  {
    id: 'prod-25',
    name: 'Mochila con Ruedas Reforzada Xtrem Boys/Girls',
    description: 'Bulto con ruedas de plástico de alta durabilidad, mango de aluminio de 3 niveles y base de PVC protectora. Excelente espacio y cierres metálicos.',
    price: 2950,
    category: 'mochilas',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 74,
    stock: 35,
    brand: 'Xtrem',
    tags: ['mochila', 'con ruedas', 'bulto', 'carrito', 'xtrem'],
    isFeatured: true,
    storePrices: { sirena: 2850, jumbo: 2890, nacional: 3100, plazalama: 2950, bravo: 2820, garrido: 2700, ole: 2750, carrefour: 3150 }
  },
  {
    id: 'prod-26',
    name: 'Lonchera Térmica Impermeable Oxford Bags',
    description: 'Lonchera escolar con aislamiento térmico de alta densidad para mantener frescos los alimentos de la merienda. Interior libre de BPA fácil de limpiar.',
    price: 850,
    category: 'mochilas',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 46,
    stock: 90,
    brand: 'Oxford Bags',
    tags: ['lonchera', 'termica', 'almuerzo', 'oxford', 'merienda'],
    isFeatured: false,
    storePrices: { sirena: 795, jumbo: 825, nacional: 890, plazalama: 850, bravo: 790, garrido: 750, ole: 765, carrefour: 920 }
  },
  {
    id: 'prod-27',
    name: 'Termo de Agua Antiderrames Contigo Kids 14oz',
    description: 'Termo infantil con tecnología Autospout antiderrames. Boquilla de silicona blanda de alta resistencia, asa de transporte y cuerpo completamente libre de BPA.',
    price: 995,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 135,
    stock: 110,
    brand: 'Contigo',
    tags: ['termo', 'agua', 'contigo', 'antiderrames', 'vaso'],
    isFeatured: true,
    storePrices: { sirena: 950, jumbo: 975, nacional: 1050, plazalama: 995, bravo: 940, garrido: 890, ole: 910, carrefour: 1090 }
  },
  {
    id: 'prod-28',
    name: 'Delantal de Pintura Plástica Infantil Maped',
    description: 'Delantal impermeable plástico transparente para proteger el uniforme escolar de manchas de témpera, pintura o pegamento. Talla única para niños de 4 a 8 años.',
    price: 220,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.4,
    reviewsCount: 33,
    stock: 100,
    brand: 'Maped',
    tags: ['delantal', 'pintura', 'protector', 'toga', 'bata'],
    isFeatured: false,
    storePrices: { sirena: 199, jumbo: 210, nacional: 235, plazalama: 220, bravo: 195, garrido: 185, ole: 190, carrefour: 240 }
  },
  {
    id: 'prod-34',
    name: 'Audífonos Escolares Acolchados con Micrófono USB',
    description: 'Audífonos estéreo de diadema regulable con control de volumen en el cable y micrófono con anulación de ruidos. Excelente para clases virtuales de inglés.',
    price: 890,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 54,
    stock: 65,
    brand: 'Genius',
    tags: ['audifonos', 'microfono', 'usb', 'virtual', 'computadora', 'tecnologia'],
    isFeatured: false,
    storePrices: { sirena: 850, jumbo: 820, nacional: 950, plazalama: 890, bravo: 830, garrido: 780, ole: 800, carrefour: 990 }
  },
  {
    id: 'prod-35',
    name: 'Memoria USB 3.2 Kingston DataTraveler Exodia 64GB',
    description: 'Unidad de almacenamiento USB 3.2 de 64 Gigas de capacidad para almacenamiento seguro de informes de proyectos, presentaciones y tareas escolares.',
    price: 495,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1624969862293-b749659ccc4e?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 203,
    stock: 250,
    brand: 'Kingston',
    tags: ['usb', 'memoria', 'pendrive', 'almacenamiento', 'kingston', 'tecnologia'],
    isFeatured: false,
    storePrices: { sirena: 450, jumbo: 470, nacional: 520, plazalama: 495, bravo: 440, garrido: 395, ole: 410, carrefour: 540 }
  },
  {
    id: 'prod-36',
    name: 'Portaminas PaperMate SharpWriter #2 x5 unidades',
    description: 'Caja con 5 portaminas mecánicos desechables con punta amortiguada y mina de grafito de 0.7mm que disminuye drásticamente las roturas de punta.',
    price: 210,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 65,
    stock: 180,
    brand: 'PaperMate',
    tags: ['portaminas', 'lapiz mecanico', 'papermate', 'escritura'],
    isFeatured: false,
    storePrices: { sirena: 195, jumbo: 189, nacional: 225, plazalama: 210, bravo: 198, garrido: 175, ole: 180, carrefour: 235 }
  },
  {
    id: 'prod-37',
    name: 'Cinta Adhesiva Invisible Scotch 3M (Doble Pack)',
    description: 'Cinta adhesiva de 19mm x 7.5m transparente de terminación opaca que permite escribir sobre ella con bolígrafo, lápiz o marcador. No amarillea.',
    price: 185,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 112,
    stock: 220,
    brand: 'Scotch 3M',
    tags: ['cinta', 'scotch', 'adhesiva', 'pegar', 'transparente'],
    isFeatured: false,
    storePrices: { sirena: 175, jumbo: 169, nacional: 199, plazalama: 185, bravo: 172, garrido: 155, ole: 160, carrefour: 205 }
  },
  {
    id: 'prod-38',
    name: 'Grapadora de Mano Compacta Zenith + Caja de Grapas x1000',
    description: 'Grapadora metálica pequeña ordinaria y portátil con capacidad para grapar hasta 12 hojas a la vez con grapas estándar No. 10.',
    price: 260,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1588611843236-407421ac1929?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 37,
    stock: 135,
    brand: 'Zenith',
    tags: ['grapadora', 'grapas', 'zenith', 'oficina', 'sujetar'],
    isFeatured: false,
    storePrices: { sirena: 239, jumbo: 245, nacional: 285, plazalama: 260, bravo: 240, garrido: 210, ole: 220, carrefour: 290 }
  },
  {
    id: 'prod-53',
    name: 'Lápices De Colores Bic Evolution 12 Und',
    description: 'Caja de 12 lápices de colores ultra-resistentes fabricados con resina sintética (sin madera). No se astillan al sacarle punta y tienen colores intensos escolares.',
    price: 235,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 94,
    stock: 310,
    brand: 'Bic',
    tags: ['colores', 'bic', 'evolution', 'dibujo', 'arte'],
    isFeatured: true,
    storePrices: { sirena: 235, jumbo: 229, nacional: 245, plazalama: 235, bravo: 230, garrido: 215, ole: 220, carrefour: 250 }
  },
  {
    id: 'prod-49',
    name: 'Sacapunta Plástico Olivo 4+1 Stabilo',
    description: 'Sacapuntas cilíndrico de alta calidad con depósito de virutas. Incluye 4 repuestos de sacapuntas interiores intercambiables + 1 de regalo.',
    price: 99,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1141?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 160,
    stock: 245,
    brand: 'Stabilo',
    tags: ['sacapuntas', 'deposito', 'stabilo', 'olivo', 'escritura'],
    isFeatured: true,
    storePrices: { sirena: 99, jumbo: 95, nacional: 105, plazalama: 99, bravo: 92, garrido: 85, ole: 88, carrefour: 109 }
  },
  {
    id: 'prod-45',
    name: 'Bolígrafo Hi-Flux Bille Azul Stabilo 10 Und',
    description: 'Caja con 10 bolígrafos de trazo ultra-suave y empuñadura ergonómica antideslizante. Tinta líquida de alto rendimiento que no se desvanece.',
    price: 549,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 78,
    stock: 110,
    brand: 'Stabilo',
    tags: ['boligrafo', 'stabilo', 'hi-flux', 'lapicero', 'azul'],
    isFeatured: true,
    storePrices: { sirena: 549, jumbo: 539, nacional: 565, plazalama: 549, bravo: 530, garrido: 510, ole: 515, carrefour: 575 }
  },
  {
    id: 'prod-41',
    name: 'Folder Carta Negro Irasa 2310',
    description: 'Folder escolar tamaño carta fabricado en cartón de fibra prensada negra de alta durabilidad y resistencia al uso diario continuo.',
    price: 19,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 412,
    stock: 1200,
    brand: 'Irasa',
    tags: ['folder', 'carta', 'negro', 'irasa', 'papelera'],
    isFeatured: false,
    storePrices: { sirena: 19, jumbo: 19, nacional: 21, plazalama: 19, bravo: 18, garrido: 17, ole: 18, carrefour: 22 }
  },
  {
    id: 'prod-56',
    name: 'Grapas Eagle 26/6 1000 Staples',
    description: 'Caja de 1,000 grapas de acero de alta resistencia y penetración para grapadoras escolares estándar de oficina y manualidades.',
    price: 65,
    category: 'tecnologia',
    image: 'https://images.unsplash.com/photo-1588611843236-407421ac1929?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 154,
    stock: 450,
    brand: 'Eagle',
    tags: ['grapas', 'eagle', 'Staples', 'grapadora', 'oficina'],
    isFeatured: false,
    storePrices: { sirena: 65, jumbo: 60, nacional: 70, plazalama: 65, bravo: 59, garrido: 55, ole: 58, carrefour: 72 }
  },
  {
    id: 'prod-46',
    name: 'Bolígrafos Keyroad Ball Pen Soft Grip 3 Pcs',
    description: 'Blíster con 3 bolígrafos ergonómicos Keyroad en colores azul, negro y rojo. Cuerpo acolchado suave que previene la fatiga manual del alumno al escribir.',
    price: 145,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1585336261022-675929945037?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 120,
    stock: 180,
    brand: 'Keyroad',
    tags: ['boligrafo', 'keyroad', 'soft grip', 'lapicero', 'escritura'],
    isFeatured: false,
    storePrices: { sirena: 145, jumbo: 139, nacional: 155, plazalama: 145, bravo: 135, garrido: 125, ole: 129, carrefour: 159 }
  },
  {
    id: 'prod-39b',
    name: 'Folder de Plástico con Elástico Portapapeles Saro',
    description: 'Folder plástico tamaño carta súper resistente con gomas elásticas en las esquinas para mantener seguros documentos escolares.',
    price: 115,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1606857521015-7f9fcf423740?q=80&w=600&auto=format&fit=crop',
    rating: 4.5,
    reviewsCount: 64,
    stock: 310,
    brand: 'Saro',
    tags: ['folder', 'plastico', 'elastico', 'portapapeles', 'saro'],
    isFeatured: false,
    storePrices: { sirena: 109, jumbo: 112, nacional: 120, plazalama: 115, bravo: 105, garrido: 99, ole: 102, carrefour: 122 }
  },
  {
    id: 'prod-60',
    name: 'Compás Escolar de Precisión Maped con Lápiz portaminas',
    description: 'Compás metálico articulado de ajuste rígido para brazos precisos y círculos consistentes de hasta 30cm de diámetro.',
    price: 195,
    category: 'escritura',
    image: 'https://images.unsplash.com/photo-1452860606245-08befc0ff44b?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 59,
    stock: 165,
    brand: 'Maped',
    tags: ['compas', 'dibujo', 'geometria', 'maped', 'matematicas'],
    isFeatured: true,
    storePrices: { sirena: 185, jumbo: 179, nacional: 215, plazalama: 195, bravo: 180, garrido: 160, ole: 168, carrefour: 215 }
  },
  {
    id: 'prod-41b',
    name: 'Caja de Lápices de Colores Staedtler Noris Club x12',
    description: 'Lápices de colores escolares clásicos con mina reforzada antirotura sistema ABS. 12 colores brillantes de alta pigmentación alemana.',
    price: 160,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 95,
    stock: 220,
    brand: 'Staedtler',
    tags: ['colores', 'staedtler', 'lapices', 'dibujo', 'arte'],
    isFeatured: false,
    storePrices: { sirena: 149, jumbo: 155, nacional: 169, plazalama: 160, bravo: 145, garrido: 135, ole: 140, carrefour: 175 }
  },
  {
    id: 'prod-42b',
    name: 'Masilla de Modelar Play-Doh Classic (Pote de 4 Colores)',
    description: 'Masilla Classic para juego moldeable no tóxica. Colores surtidos brillantes ideales para actividades creativas sensoriales de preescolar.',
    price: 395,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1560421683-6856ea585c78?q=80&w=600&auto=format&fit=crop',
    rating: 4.9,
    reviewsCount: 150,
    stock: 85,
    brand: 'Play-Doh',
    tags: ['masilla', 'play-doh', 'moldeable', 'preescolar', 'manualidad'],
    isFeatured: false,
    storePrices: { sirena: 375, jumbo: 380, nacional: 410, plazalama: 395, bravo: 365, garrido: 345, ole: 350, carrefour: 425 }
  },
  {
    id: 'prod-43b',
    name: 'Marcadores Finos Faber-Castell Fiesta (Caja de 12)',
    description: 'Rotuladores escolares de punta fina de colores intensos y brillantes. Tapón ventilado de seguridad y tinta con base de agua lavable.',
    price: 290,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.8,
    reviewsCount: 74,
    stock: 140,
    brand: 'Faber-Castell',
    tags: ['marcadores', 'fiesta', 'faber-castell', 'color', 'fino'],
    isFeatured: false,
    storePrices: { sirena: 275, jumbo: 269, nacional: 299, plazalama: 290, bravo: 270, garrido: 250, ole: 255, carrefour: 310 }
  },
  {
    id: 'prod-44b',
    name: 'Cuaderno de Dibujo Súper Saro 40 Hojas',
    description: 'Cuaderno espiral especial para expresión artística infantil y dibujo, hojas blancas de cartulina suave de 90g de grosor para aguantar creyones y témperas.',
    price: 165,
    category: 'cuadernos',
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600&auto=format&fit=crop',
    rating: 4.6,
    reviewsCount: 48,
    stock: 190,
    brand: 'Saro',
    tags: ['cuaderno', 'dibujo', 'saro', 'espiral', 'blanco'],
    isFeatured: false,
    storePrices: { sirena: 155, jumbo: 159, nacional: 175, plazalama: 165, bravo: 150, garrido: 140, ole: 145, carrefour: 180 }
  },
  {
    id: 'prod-45b',
    name: 'Témperas Acrílicas Artísticas Giotto x6 Colores',
    description: 'Set de 6 botes de témpera acrílica lista para su uso escolar. Colores ricos y de máxima cobertura fáciles de mezclar.',
    price: 245,
    category: 'arte',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&auto=format&fit=crop',
    rating: 4.7,
    reviewsCount: 66,
    stock: 110,
    brand: 'Giotto',
    tags: ['temperas', 'giotto', 'acrilico', 'pincel', 'arte'],
    isFeatured: false,
    storePrices: { sirena: 235, jumbo: 230, nacional: 255, plazalama: 245, bravo: 220, garrido: 210, ole: 215, carrefour: 265 }
  }
];

export const SCHOOLS = [
  'Colegio Dominicano De La Salle',
  'Colegio Loyola (RD)',
  'Colegio Babeque Secundaria',
  'Colegio Carol Morgan School',
  'Colegio Amador',
  'Colegio Saint George School',
  'Liceo República de Argentina',
  'Otro Colegio (Lista General RD)'
];

export const GRADES = [
  'Kínder / Preescolar',
  '1ro de Primaria',
  '3ro de Primaria',
  '5to de Primaria',
  '1ro de Secundaria (7mo)',
  '3ro de Secundaria (9no)',
  '5to de Secundaria (11mo)'
];

export const SCHOOL_LISTS_DATA: SchoolList[] = [
  {
    id: 'list-01',
    schoolName: 'Colegio Dominicano De La Salle',
    grade: '1ro de Primaria',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 6, isRequired: true, notes: 'Colores azul, verde y rojo para materias básicas' },
      { productId: 'prod-02', name: 'Cuaderno de Caligrafía Mascot 60 Hojas', quantity: 2, isRequired: true, notes: 'Para práctica semanal' },
      { productId: 'prod-09', name: 'Lápiz Grafito Mongol #2 Premium (Caja de 12)', quantity: 2, isRequired: true, notes: 'Tener siempre 3 lápices amolados en el estuche' },
      { productId: 'prod-03', name: 'Caja de Lápices de Colores Prismacolor Junior x24', quantity: 1, isRequired: true },
      { productId: 'prod-10', name: 'Juego de Geometría Escolar Maped 4 Piezas', quantity: 1, isRequired: true },
      { productId: 'prod-11', name: 'Pegamento Escolar Líquido Elmers Blanco 4oz', quantity: 2, isRequired: true },
      { productId: 'prod-14', name: 'Tijera Escolar Punta Roma Maped Koopy 5"', quantity: 1, isRequired: true }
    ]
  },
  {
    id: 'list-02',
    schoolName: 'Colegio Dominicano De La Salle',
    grade: '5to de Secundaria (11mo)',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 8, isRequired: true, notes: 'Uno por materia general' },
      { productId: 'prod-08', name: 'Calculadora Científica Casio fx-82MS 2nd Edition', quantity: 1, isRequired: true, notes: 'Obligatorio en Matemática Avanzada y Física' },
      { productId: 'prod-05', name: 'Bolígrafos Bic Cristal Precision Azul (Caja de 10)', quantity: 1, isRequired: true },
      { productId: 'prod-12', name: 'Corrector en Cinta Liquid Paper Dryline Pro', quantity: 2, isRequired: true },
      { productId: 'prod-10', name: 'Juego de Geometría Escolar Maped 4 Piezas', quantity: 1, isRequired: true },
      { productId: 'prod-15', name: 'Marcador Resaltador Faber-Castell Pastel (Set de 4)', quantity: 1, isRequired: false, notes: 'Opcional para resúmenes estéticos' }
    ]
  },
  {
    id: 'list-03',
    schoolName: 'Colegio Loyola (RD)',
    grade: '3ro de Primaria',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 8, isRequired: true },
      { productId: 'prod-09', name: 'Lápiz Grafito Mongol #2 Premium (Caja de 12)', quantity: 1, isRequired: true },
      { productId: 'prod-03', name: 'Caja de Lápices de Colores Prismacolor Junior x24', quantity: 1, isRequired: true },
      { productId: 'prod-11', name: 'Pegamento Escolar Líquido Elmers Blanco 4oz', quantity: 1, isRequired: true },
      { productId: 'prod-14', name: 'Tijera Escolar Punta Roma Maped Koopy 5"', quantity: 1, isRequired: true },
      { productId: 'prod-13', name: 'Bloque de Plastilina Faber-Castell 10 Colores', quantity: 2, isRequired: true, notes: 'Para maquetas de Ciencias e Historia Dominicana' }
    ]
  },
  {
    id: 'list-04',
    schoolName: 'Otro Colegio (Lista General RD)',
    grade: 'Kínder / Preescolar',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-13', name: 'Bloque de Plastilina Faber-Castell 10 Colores', quantity: 3, isRequired: true, notes: 'Estimulación motora primordial' },
      { productId: 'prod-06', name: 'Estuche de Témperas Pelikan x12 Colores + Pincel', quantity: 1, isRequired: true },
      { productId: 'prod-11', name: 'Pegamento Escolar Líquido Elmers Blanco 4oz', quantity: 2, isRequired: true },
      { productId: 'prod-14', name: 'Tijera Escolar Punta Roma Maped Koopy 5"', quantity: 1, isRequired: true },
      { productId: 'prod-03', name: 'Caja de Lápices de Colores Prismacolor Junior x24', quantity: 1, isRequired: true }
    ]
  },
  {
    id: 'list-05',
    schoolName: 'Colegio Babeque Secundaria',
    grade: '3ro de Secundaria (9no)',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 10, isRequired: true, notes: 'Portadas de colores diferentes por materia' },
      { productId: 'prod-08', name: 'Calculadora Científica Casio fx-82MS 2nd Edition', quantity: 1, isRequired: true, notes: 'Necesaria para Álgebra del grado' },
      { productId: 'prod-05', name: 'Bolígrafos Bic Cristal Precision Azul (Caja de 10)', quantity: 1, isRequired: true },
      { productId: 'prod-12', name: 'Corrector en Cinta Liquid Paper Dryline Pro', quantity: 1, isRequired: true },
      { productId: 'prod-10', name: 'Juego de Geometría Escolar Maped 4 Piezas', quantity: 1, isRequired: true },
      { productId: 'prod-15', name: 'Marcador Resaltador Faber-Castell Pastel (Set de 4)', quantity: 2, isRequired: false }
    ]
  },
  {
    id: 'list-06',
    schoolName: 'Colegio Carol Morgan School',
    grade: '1ro de Secundaria (7mo)',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 8, isRequired: true },
      { productId: 'prod-07', name: 'Resma de Papel Satinado Premium Letter / Carta 500H', quantity: 1, isRequired: true, notes: 'Entregar al tutor de lengua española' },
      { productId: 'prod-05', name: 'Bolígrafos Bic Cristal Precision Azul (Caja de 10)', quantity: 1, isRequired: true },
      { productId: 'prod-12', name: 'Corrector en Cinta Liquid Paper Dryline Pro', quantity: 1, isRequired: true },
      { productId: 'prod-15', name: 'Marcador Resaltador Faber-Castell Pastel (Set de 4)', quantity: 1, isRequired: true },
      { productId: 'prod-04', name: 'Mochila Escolar Porta-Laptop Ergonómica Oxford', quantity: 1, isRequired: false, notes: 'Se recomienda mochila protectora para Chromebooks' }
    ]
  },
  {
    id: 'list-07',
    schoolName: 'Colegio Amador',
    grade: '3ro de Primaria',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 5, isRequired: true },
      { productId: 'prod-02', name: 'Cuaderno de Caligrafía Mascot 60 Hojas', quantity: 2, isRequired: true },
      { productId: 'prod-09', name: 'Lápiz Grafito Mongol #2 Premium (Caja de 12)', quantity: 2, isRequired: true },
      { productId: 'prod-03', name: 'Caja de Lápices de Colores Prismacolor Junior x24', quantity: 1, isRequired: true },
      { productId: 'prod-11', name: 'Pegamento Escolar Líquido Elmers Blanco 4oz', quantity: 1, isRequired: true },
      { productId: 'prod-14', name: 'Tijera Escolar Punta Roma Maped Koopy 5"', quantity: 1, isRequired: true }
    ]
  },
  {
    id: 'list-08',
    schoolName: 'Colegio Saint George School',
    grade: '1ro de Primaria',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 6, isRequired: true },
      { productId: 'prod-02', name: 'Cuaderno de Caligrafía Mascot 60 Hojas', quantity: 1, isRequired: true },
      { productId: 'prod-03', name: 'Caja de Lápices de Colores Prismacolor Junior x24', quantity: 1, isRequired: true },
      { productId: 'prod-13', name: 'Bloque de Plastilina Faber-Castell 10 Colores', quantity: 1, isRequired: true },
      { productId: 'prod-11', name: 'Pegamento Escolar Líquido Elmers Blanco 4oz', quantity: 2, isRequired: true },
      { productId: 'prod-14', name: 'Tijera Escolar Punta Roma Maped Koopy 5"', quantity: 1, isRequired: true }
    ]
  },
  {
    id: 'list-09',
    schoolName: 'Liceo República de Argentina',
    grade: '5to de Primaria',
    academicYear: '2026-2027',
    items: [
      { productId: 'prod-01', name: 'Cuaderno Cosido Línea Rayado Mascot RD', quantity: 12, isRequired: true, notes: 'Para uso diario en el aula' },
      { productId: 'prod-09', name: 'Lápiz Grafito Mongol #2 Premium (Caja de 12)', quantity: 2, isRequired: true },
      { productId: 'prod-05', name: 'Bolígrafos Bic Cristal Precision Azul (Caja de 10)', quantity: 1, isRequired: true },
      { productId: 'prod-03', name: 'Caja de Lápices de Colores Prismacolor Junior x24', quantity: 1, isRequired: true },
      { productId: 'prod-10', name: 'Juego de Geometría Escolar Maped 4 Piezas', quantity: 1, isRequired: true },
      { productId: 'prod-11', name: 'Pegamento Escolar Líquido Elmers Blanco 4oz', quantity: 1, isRequired: true }
    ]
  }
];
